version: "3"

services:
  hive:
    build: .
    entrypoint: /init-hive.sh
    ports:
      - "9083:9083"
      - "10000:10000"
    networks:
      - network1
networks:
  network1:
    name: default_network
    external: true
